### ISSUE TITLE
code and ckpts

### ISSUE THREAD

**Issue by MahdiMohseni0033** [lzw-lzw/GroundingGPT#1]
Hi,
Thanks for your amazing work ? 
could you update us about the time of release code and ckpts?

**Comment by lzw-lzw** [comment]
Hi, thanks for your attention, we will release our code and ckpts next month.

**Comment by trouble-maker007** [comment]
@lzw-lzw any update？

**Comment by 9bow** [comment]
Hello, @lzw-lzw
I also wonder if there is any timeline for code.
Thanks!

**Comment by lntzm** [comment]
Waiting for updates

**Comment by lzw-lzw** [comment]
We have released our code, and we will release our dataset and model soon.

**Comment by 9bow** [comment]
Thank you, @lzw-lzw
I’m also looking forward to seeing the dataset and model weights soon! 😃
