### ISSUE TITLE
Evaluation Code

### ISSUE THREAD

**Issue by Jiahaohong** [lzw-lzw/GroundingGPT#4]
Great work！Could you release the evaluation code?

**Comment by ee2110** [comment]
The idea is great, I also would like to have a reference on the evaluation code, especially for video temporal grounding task on Charades-STA. I also wondering if the result from other baselines such as Video-LLaMA, VideoChat, Video-ChatGPT is collected from experiment conducted by GroundingGPT's author.

**Comment by lzw-lzw** [comment]
Thank you for your attention. Our evaluation utilizes the code repositories of LLaVA, Ferret, and Video-ChatGPT, and you can directly use the evaluation code provided by these repositories. As for the results on the Charades-STA dataset, we used the testing results provided in the VTimeLLM paper.
