### ISSUE TITLE
What is the hardware requirements for running the gradio-demo/inference?

### ISSUE THREAD

**Issue by wematan** [lzw-lzw/GroundingGPT#6]
Hi, 
I'm running a RTX4080 (16GB) on my pc, but was unable to run the project due to OOM errors,
From inspecting the code it seems like there a lot of model loading happening (CLIP, imagebind, audio encoder)
also, there are stale flags (load_8bit, load_4bit) which are not used at all when loading the models.
Any advise?

**Comment by lzw-lzw** [comment]
Thank you for your attention. Based on our experience, inference requires at least 24GB of GPU memory. The loaded models you mentioned, such as Imagebind (used to extract audio features), are necessary for inference. Our current version of the code does not utilize 8-bit/4-bit quantization. If we have time, we will modify the code to support this, or you can refer to LLaVA for modification, which should not be too difficult. Thanks!
