### ISSUE TITLE
Garbled answer

### ISSUE THREAD

**Issue by devinhee** [lzw-lzw/GroundingGPT#8]
Human: hello, Please describe the image
Assistant: /home/devin/py3.10/lib/python3.10/site-packages/transformers/generation/utils.py:1421: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use and modify the model generation configuration (see https://huggingface.co/docs/transformers/generation_strategies#default-text-generation-configuration )
  warnings.warn(
scalesննেicніципа康 него官 éx wichtachmentadóնorroworrow éx негоDataSet него Patri него éxel clearly него scales BRorrow ENгово postingိBasic éxে негољи него éx него Ja aur него scalesնadóնљи")` aurValueadóে EN него convenient éxbaut него convenient convenient éx happel него teor Schweiz EventValue")` Mex Mex негоussen THachment aurel него康 Mex негоে analogে weerel scales BR негоBasic Mexেitting Event teor¹orrowValueperión weerzsেгнеel Eventљи éxtt clearly scales scales filsնorrowevArguments ENেDurationেadóBasic éx putப DAT éx негоoningelBasicDataSet éxणadó")` éxelhanced Brown Schweiz")`per")`DataSet scalesն Mex postingoningмираacia MexValue teor")`Ω BR негоে aur Mexেেión champion micro happttirusdimensional Patriն aurorrow негоArgumentsel官ussen aur happrown него него EN проводиArguments latin auritting Eventcychে.: Chris latin aur put негоcych Inside aurљиেoning aur негољи MexেDEX Chrisevelittingেcych Meteriónhanced scales éxorrowնে Eventellettorrow Mex analogoning DAT Mexel teor него posting Mexper Chrisorrowն Mex него TH")`adóΩ happorrowussen posting него Ja")`DataSet putљи Mexrownoningadóev happbautেেoreelrijk aurে weer EN官 Mexмираitting Mexoning官েেoningে éx Mex него ENiónpercychrijk")` aur")` Artenে")` convenient convenientмираevে éxেmn MexেেΩceptor happorrow Mexcontreadóபেгне éx官 posting него éxevelে scales")` teor Schweizে Mexadó filsrijk")` Mex Mex posting BRadó éxel teoriónEMAն scales")` wicht éx happে micrott Event filsrijk convenientevelorrow негоেadóDuration fancy aur MexValueেcychorrow posting happ BR posting posting негоে.: Ja Mex convenientussenzs DATDataSetে fancy éx EN негоadóadó aur него auradó Ja Mex негоitting Jabaut aurevেorrow aurљи康љи")` него championcjiেљи него Mexdimensionaladó fancy менмирагне éx негоussenrijkbautљиেevে filsгне happ clearly éxण негоেoreљи teor него Mexel scalesrijk scalesDataSetachmentadóেљи wicht Ja Meter Mex Ja негоussen EN Schweiz fils него teor官ে Obviouslyে éxն Ja Ja негоে aur官 convenient analog негоakespe Mex官 éxadó posting clearly posting scales wichtorrowzs него aur него wichtel Mex негоorrow éx

**Comment by lzw-lzw** [comment]
Hi, if you are using cli.py for the conversation, you need to switch the input modality by inputing "change image/video/sound"(as shown in https://github.com/lzw-lzw/GroundingGPT/blob/1f3f53e5e899b7ae24fe3c8b8bdc803ba66a3f0a/lego/serve/cli.py#L29) and then provide the path to the image before chatting with the model. However, your problem seems more likely to be caused by the environment, can you provide more details, such as your environment and the command you are running?
